### ISSUE TITLE
Crash with custom dpi

### ISSUE THREAD

**Issue by mirh** [farmerbriantee/AgOpenGPS#194]
As I had already complained in https://github.com/farmerbriantee/AgOpenGPS/issues/48#issuecomment-663770707
```
Application: AgOpenGPS.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at AgOpenGPS.FormGPS.LineUpManualBtns()
   at AgOpenGPS.FormGPS.FixPanelsAndMenus(Boolean)
   at AgOpenGPS.FormGPS.FormGPS_Resize(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnResize(System.EventArgs)
   at System.Windows.Forms.Form.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Form.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.ScrollableControl.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Form.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   at System.Windows.Forms.ContainerControl.Scale(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean, Boolean)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean)
   at System.Windows.Forms.Control.ResumeLayout(Boolean)
   at AgOpenGPS.FormGPS.InitializeComponent()
   at AgOpenGPS.FormGPS..ctor()
   at AgOpenGPS.Program.Main()
```
On W10 you will need **custom** dpi factors (as opposed to even the standard fixed "25%" increments in W7), but still.

**Comment by mirh** [comment]
Hello?? This is a serious bug that is gonna affect a lot of people.

**Comment by richardklasens** [comment]
How about this in the latest source?

**Comment by mirh** [comment]
Yes this bug is still in the latest sources. 
I don't know what's the point of closing them all regardless of their merit.

**Comment by farmerbriantee** [comment]
What is the solution? Any idea?

**Comment by mirh** [comment]
Nope, but considering it has workarounds, no hurry. 
I suppose you have far worse nuts to crack on release week. 

Just.. read stuff before mass nuking it from orbit.

**Comment by farmerbriantee** [comment]
I did, others did, no problem

**Comment by farmerbriantee** [comment]
issues were removed because we are on v5 and no one will be fixing v4, 

If they are actual issues still, they will magically appear again and can be dealt with

**Comment by farmerbriantee** [comment]
The other really helpful thing is coming up with a solution to a problem no one on the development team can replicate. If we can't make it crash, we can't fix a problem that doesn't exist.

**Comment by mirh** [comment]
Normal practice is that you bump the thread and ask the author for an update, and if you get no answer after a given number of days you close it. 
Then, I get that v5 is a big beefy new version, but it's not like a total rewrite. And even totally legit and "abstract" questions like #170 have been sent to oblivion. 

Anyway, this is so weird since I can reproduce it on all my pcs instead. 
If you are on W10, did you set the custom scaling to 115% for example?

**Comment by farmerbriantee** [comment]
So i tried custom scaling of 157, 167, and normal scaling of 150, 175, 200. Works just fine.

**Comment by farmerbriantee** [comment]
I should mention there is a discussion forum which gets read a lot. This issues page, not very much.

**Comment by mirh** [comment]
I know... 
But my line of thought was always "that's for chit-chat", "this is for serious business". 

Anyhow, I really don't know what else I can add. 
W7 has latest .NET 4.8, while W10 has whatever comes out of the box with 20H2. 
The crash is just trying to open the program like at all, and together with #176 (which is supposedly no more) I no-joke spent an entire week banging my head on these crazy "pixels size" matters.

**Comment by farmerbriantee** [comment]
> I know...
> But my line of thought was always "that's for chit-chat", "this is for serious business".
> 
If you want a question answered promptly and looked at, post it in the chit chat.  :)

Here is the answer to your angvel questions as well:

Sure can, angvel isn't actually used and adding 2pi several years ago made it easy for setting the value against a slider - none of which is used anymore anyway.

And also it isn't the actual steer angle, its the desired steer angle to get to the line - not what the vehicle is actually steering. Always remember AOG is a video game - it doesn't have to be correct or follow physics - it just needs to work. And even more confusing, it isn't even velocity, its the formula for acceleration.

**Comment by expltu** [comment]
It is caused by custom scaling. Mine was set tio 105% - and the app was crashing. 
![image](https://user-images.githubusercontent.com/32002301/151043619-e747013a-41ca-40dc-ad92-c2eaab8abfac.png)

**Comment by mirh** [comment]
QED.

**Comment by mirh** [comment]
I'm once again pointing out this still happens.
